config/routes.rb
Rails.application.routes.draw do
  root :to => 'albums#index'

  resources :albums do
    resources :songs
  end

  resources :albums do
    resources :reviews
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :songs
  has_many :reviews

  validates :artist_name, :album_name, :genre, :presence => true
  scope :alphabetize, -> { order('artist_name ASC')}
  scope :most_reviews, -> {(
    select("albums.id, albums.album_name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("albums.id")
    .order("reviews_count DESC")
    .limit(5))}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :album

  validates :username, :content, :album_id, :rating, :presence => true

  scope :ten_most_recent, -> { order(created_at: :desc).limit(10) }
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album  
  validates :title, :album_id, :presence => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
    @alphabetize_albums = @albums.alphabetize
    @most_reviews = @albums.most_reviews
  end

  def new
    @album = Album.new
  end

  def show
   @album = Album.find(params[:id])
   @songs = Song.all
   @song = Song.find(@album.id)
   @reviews = Review.all
   @ten_most_recent = Review.ten_most_recent

 end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:notice] = "Artist successfully added!"
      redirect_to  albums_path
    else
      flash[:alert] = "Sorry, error!"
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album= Album.find(params[:id])
    if @album.update(album_params)
      redirect_to albums_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
  end

private
  def album_params
    params.require(:album).permit(:artist_name, :album_name, :genre)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    @album = Album.find(params[:album_id])
    @review = @album.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Album successfully added!"
      redirect_to album_path(@album)
    else
      flash[:alert] = "Sorry, error!"
      render :new
    end
  end

  private
    def review_params
      params.require(:review).permit(:username, :content, :rating)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def show
    @song = Song.find(params[:id])
  end

  def create
    @album = Album.find(params[:album_id])
    @song = @album.songs.new(song_params)
    if @song.save
      flash[:notice] = "Song successfully added!"
      redirect_to album_path(@album)
    else
      flash[:alert] = "Sorry, error!"
      render :new
    end
  end

private
  def song_params
    params.require(:song).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%= render "layouts/errors", :object => @album %>

<%= form_for @album do |f| %>
  <%= f.label :artist_name %>
  <%= f.text_field :artist_name %>
  <%= f.label :album_name %>
  <%= f.text_field :album_name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit  %>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit album</h1>

<%= render "form" %>

app/views/albums/index.html.erb
<div class="jumbotron">
  <p>Artist Fan Site</p>
</div>

<h1>Click an Artist below to see their Albums:</h1>

<div class="container" id="home-artists">
  <% @alphabetize_albums.each do |album| %>
      <div class="card">
        <h3><em><%= link_to album.artist_name, album_path(album) %></em></h3>

      </div>
  <% end %>
</div>

<br>
<div class="album-reviews">
  <div class="card">
    <h4>Most reviewed albums:</h4>
    <% @most_reviews.each do |album| %>
      <h3><em><%= link_to album.album_name, album_path(album) %></em></h3>
      <% end %>
  </div>
</div>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render "form" %>

app/views/albums/show.html.erb
<div class="container">
  <h3><em><%= @album.artist_name %></em></h3>
  <h4>Album Name:</h4><p><%= @album.album_name %></p>
  <h4>Genre:</h4><p><%= @album.genre %></p>

  <% if @album.songs.any? %>
    <h4>Songs:</h4>

    <ol>
    <% 10.times do |song| %>
      <li><%= @song.title %></li>
    <% end %>
    </ol>
  <% else %>
    <p><%= link_to "Add a Song", new_album_song_path(@album) %></p>
  <% end %>

  <p>Last Ten Reviews:</p>
  <% @ten_most_recent.each do |review| %>
    <p><%= review.username %></p>
    <p><%= review.content %></p>
    <p><%= review.rating %></p>
  <% end %>


  <% if @album.reviews.any? %>
    <h4>Reviews:</h4>

    <ol>
    <% @album.reviews.each do |review| %>
      <p><%= review.username %></p>
      <p><%= review.content %></p>
      <p><%= review.rating %></p>
    <% end %>
    </ol>
  <% else %>
    <p><%= link_to "Add a Review", new_album_review_path(@album) %></p>
  <% end %>

  <p><%= link_to "Back to Artist", root_path %></p>
  <p><%= link_to "Edit Artist", edit_album_path %></p>
  <p><%= link_to "Delete Artist", album_path(@album),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FanSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <header class="navbar  navbar-inverse">
     <div class="navbar-class">
       <div class="container">
         <ul class="nav navbar-nav">
           <li class="active"><a href="/">HOME</a></li>
           <li><%=link_to "Add New Album", new_album_path%></li>
         </ul>
       </div>
       </div>
     </header>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@album, @review], url: {action: "create"} do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :content, 'Comment' %>
  <%= f.text_field :content%>
  <%= f.label :rating, "Rating 1-5 (1 being the worst, 5 being the best)" %>
  <%= f.text_field :rating%>
  <p><%= f.submit  %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>Leave a Review</h1>

<%= render "form" %>

app/views/songs/_form.html.erb
<%= render "layouts/errors", :object => @song %>

<%= form_for [@album, @song], url: {action: "create"} do |f| %>
  <%= f.hidden_field :album_id, :value => params[:album_id] %>
  <%= f.hidden_field :album_name, :value => params[:album_name] %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <p><%= f.submit  %></p>
<% end %>

app/views/songs/new.html.erb
<h1>New Song Name</h1>

<%= render "form" %>

app/views/songs/show.html.erb
<h3><em><%= @song.title %></em></h3>